version: 2

updates:
  - package-ecosystem: pipenv  # Poetry is treated similarly to pipenv for Dependabot
    directory: "/"
    schedule:
      interval: weekly
      time: "02:00"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "02:00"
