[tool.poetry]
name = "boxmot"
version = "10.0.52"
description = "BoxMOT: pluggable SOTA tracking modules for segmentation, object detection and pose estimation models"
authors = ["Mikel Broström"]
license = "AGPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
filterpy = "^1.4.5"
gdown = "^5.1.0"
lapx = "^0.5.5"
loguru = "^0.7.2"
numpy = "1.24.4"
pyyaml = "^6.0.1"
regex = "^2023.12.25"
torch = "^2.0.0+cpu"
torchvision = "^0.17.1"
yacs = "^0.1.8"

[tool.poetry.group.test.dependencies]
pytest = "^8.0.2"
isort = "^5.13.2"
pytest-cov = "^4.1.0"

[tool.poetry.group.yolo.dependencies]
ultralytics = {git = "https://github.com/mikel-brostrom/ultralytics.git"}

[tool.poetry.group.export.dependencies]
onnx = "^1.15.0"
onnxsim = "^0.4.36"
openvino-dev = "^2023.3.0"

[tool.poetry.group.evolve.dependencies]
optuna = "^3.5.0"
plotly = "^5.19.0"
joblib = "^1.3.2"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
