# bytetrack_search_space.yaml

track_thresh:
  type: uniform
  range: [0.4, 0.6]

track_buffer:
  type: randint
  range: [10, 61, 10]  # The upper bound is exclusive, step size of 10

match_thresh:
  type: uniform
  range: [0.7, 0.9]