# imprassoc_search_space.yaml

track_high_thresh:
  type: uniform
  range: [0.3, 0.7]

track_low_thresh:
  type: uniform
  range: [0.1, 0.3]

new_track_thresh:
  type: uniform
  range: [0.1, 0.8]

track_buffer:
  type: qrandint
  range: [20, 80, 10]  # The upper bound is exclusive, step size of 10

match_thresh:
  type: uniform
  range: [0.1, 0.9]

second_match_thresh:
  type: uniform
  range: [0.1, 0.4]

overlap_thresh:
  type: uniform
  range: [0.3, 0.6]

proximity_thresh:
  type: uniform
  range: [0.1, 0.8]

appearance_thresh:
  type: uniform
  range: [0.1, 0.8]

cmc_method:
  type: choice
  options: ['sparseOptFlow']

frame_rate:
  type: choice
  options: [30]

lambda_:
  type: uniform
  range: [0.97, 0.995]
