name: Publish to PyPI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      pypi:
        type: boolean
        description: Publish to PyPI

jobs:
  pypi-upload:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Increase path version and get commit message
        id: get_version
        run: |
          git config --local user.email yolov5.deepsort.pytorch@gmail.com
          git config --local user.name mikel-brostrom
          commit_message=$(poetry version patch)
          git add pyproject.toml
          poetry build
          echo "commit_message={$commit_message}" >> $GITHUB_OUTPUT
        if: ${{ success() }}

      - name: Commit and push updated version
        run: |
          git commit -m "${{ steps.get_version.outputs.commit_message }}"
          git push
        if: ${{ success() }}

      - name: Publish to PyPI
        run: poetry publish --build --verbose
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        if: ${{ success() }}

      - name: Create code release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.increment_version.outputs.new_version }}
          release_name: Release v${{ steps.increment_version.outputs.new_version }}
          draft: false
          prerelease: false
        if: ${{ success() }}
