# name of the workflow, what it is doing (optional)
name: Tracking with segmentation model test

# events that trigger the workflow (required)
on:
  push:
    branches:
      - parallelize-trackers-ci-tests
  pull_request:
    # pull request where master is target
    branches:
      - master

env:
  # Directory of PyPi package to be tested
  PACKAGE_DIR: boxmot

jobs:
  test-tracking-with-seg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -e . --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Test tracking with seg models
      env:
        IMG: ./assets/MOT17-mini/train/MOT17-02-FRCNN/img1/000001.jpg
      run: python examples/track.py --tracking-method deepocsort --yolo-model yolov8n-seg.pt --source $IMG