# name of the workflow, what it is doing (optional)
name: Tests

# events that trigger the workflow (required)
on:
  push:
    branches: [main]
  pull_request:
    # pull request where master is target
    branches: [main]

env:
  # Directory of PyPi package to be tested
  PACKAGE_DIR: boxmot

jobs:
  test-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: 
        python -m pip install --upgrade pip setuptools wheel
        pip install -e . pytest pytest-cov --extra-index-url https://download.pytorch.org/whl/cpu

    - name: Pytest tests  # after tracking options as this does not download models
      shell: bash  # for Windows compatibility
      run: |
        # needed in TFLite export
        wget https://github.com/PINTO0309/onnx2tf/releases/download/1.16.31/flatc.tar.gz
        tar -zxvf flatc.tar.gz
        sudo chmod +x flatc
        sudo mv flatc /usr/bin/

        pytest --cov=$PACKAGE_DIR --cov-report=html -v tests
        coverage report --fail-under=$COVERAGE_FAIL_UNDER