# name of the workflow, what it is doing (optional)
name: all tracking methods test

# events that trigger the workflow (required)
on:
  push:
    branches: [master, ci-test]
  pull_request:
    # pull request where master is target
    branches: [master]

env:
  # Directory of PyPi package to be tested
  PACKAGE_DIR: boxmot

jobs:
  test-tracking-methods:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]   # skip windows-latest for
        python-version: ['3.8', '3.9', '3.10']
        tracking-method: [hybridsort, botsort, ocsort, bytetrack]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 50
    steps:
      - uses: actions/checkout@v4  # Check out the repository
      - name: Set up Python
        uses: actions/setup-python@v5  # Prepare environment with python 3.9
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies

      - name: Install requirements
        shell: bash  # for Windows compatibility
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e . --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Generate detections and embeddings
        run: |
          python experimentation/generate_dets_and_embs.py --source ./assets/MOT17-mini/train --yolo-model yolov8n.pt --reid-model osnet_x0_25_msmt17.pt --imgsz 320
          python experimentation/track_w_dets_n_embs.py --dets yolov8n --reid osnet_x0_25_msmt17

      - name: Run tracking method
        run: |
          python experimentation/track_w_dets_n_embs.py --tracking-method ${{ matrix.tracking-method }} --dets yolov8n --reid osnet_x0_25_msmt17 --imgsz 320